#!/bin/sh

## Lint .js-files
ROOT_DIR=$(git rev-parse --show-toplevel)
LINTSCRIPT="${ROOT_DIR}/bin/jslint_uncommitted.js"
for file in $(git diff-index --name-only --cached HEAD -- | grep '\.js$'); do
  if node $LINTSCRIPT $file 2>&1 | grep 'JSLint OK'; then
    echo "JSLint completed on: ${file}"
    exit 0
  else
    node $LINTSCRIPT $file
    exit 1
  fi
done
exit 0